sonar.projectKey=packet-quest-arena
sonar.projectName=Packet Quest Arena

sonar.sources=backend/src/main,frontend/src,simulator
sonar.tests=backend/src/test,frontend/src,simulator/tests

sonar.java.binaries=backend/target/classes
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=simulator/coverage.xml
