package com.packetquest.service;

import com.packetquest.dto.RouteActionRequest;
import com.packetquest.exception.SessionNotFoundException;
import com.packetquest.factory.PacketFlowFactory;
import com.packetquest.factory.TopologyFactory;
import com.packetquest.model.GameSession;
import com.packetquest.model.Link;
import com.packetquest.model.PacketFlow;
import com.packetquest.model.Player;
import com.packetquest.repository.GameSessionRepository;
import com.packetquest.repository.LinkRepository;
import com.packetquest.repository.NodeRepository;
import com.packetquest.repository.PacketFlowRepository;
import com.packetquest.repository.PlayerRepository;
import com.packetquest.service.scoring.ScoringStrategy;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;
import static org.mockito.ArgumentMatchers.anyList;

class GameServiceTest {

    private GameSessionRepository sessionRepo;
    private PlayerRepository playerRepo;
    private NodeRepository nodeRepo;
    private LinkRepository linkRepo;
    private PacketFlowRepository flowRepo;
    private TopologyFactory topologyFactory;
    private PacketFlowFactory flowFactory;
    private ScoringStrategy scoringStrategy;
    private GameService service;

    private GameSession session;
    private Player player;
    private PacketFlow flow;

    @BeforeEach
    void setUp() {
        sessionRepo = mock(GameSessionRepository.class);
        playerRepo = mock(PlayerRepository.class);
        nodeRepo = mock(NodeRepository.class);
        linkRepo = mock(LinkRepository.class);
        flowRepo = mock(PacketFlowRepository.class);
        topologyFactory = mock(TopologyFactory.class);
        flowFactory = mock(PacketFlowFactory.class);
        scoringStrategy = mock(ScoringStrategy.class);
        when(scoringStrategy.calculate(anyList(), anyList())).thenReturn(0);

        service = new GameService(sessionRepo, playerRepo, nodeRepo, linkRepo,
                flowRepo, topologyFactory, flowFactory, scoringStrategy);
        // Common fixture: session "S1" with player 100 and a flow 1→4, bandwidth 10
        session = new GameSession();
        // session.id is set in the constructor; capture whatever it is and reuse it
        when(sessionRepo.findById(session.getId())).thenReturn(Optional.of(session));

        player = new Player();
        player.setName("alice");
        player.setSession(session);
        // Player.id is auto-generated by JPA; tests use the mock so id can be null,
        // but we look up by an explicit id below, so set a fixed one via reflection-free trick:
        when(playerRepo.findById(100L)).thenReturn(Optional.of(player));

        flow = new PacketFlow();
        flow.setSourceNodeId(1L);
        flow.setDestinationNodeId(4L);
        flow.setBandwidth(10);
        flow.setStatus("PENDING");
        flow.setSession(session);
        when(flowRepo.findById(1L)).thenReturn(Optional.of(flow));

        // One link 1↔4 in this session
        Link link = new Link();
        link.setSource(1L);
        link.setTarget(4L);
        link.setCapacity(100);
        link.setLatency(10);
        link.setLoad(0);
        link.setStatus("UP");
        link.setSession(session);
        when(linkRepo.findBySessionId(session.getId())).thenReturn(List.of(link));
        when(linkRepo.save(any(Link.class))).thenAnswer(inv -> inv.getArgument(0));
        when(flowRepo.save(any(PacketFlow.class))).thenAnswer(inv -> inv.getArgument(0));
    }

    private RouteActionRequest req(Long playerId, Long flowId, List<Long> path) {
        RouteActionRequest r = new RouteActionRequest();
        r.setPlayerId(playerId);
        r.setFlowId(flowId);
        r.setPath(path);
        return r;
    }

    @Test
    void unknownSession_throwsSessionNotFound() {
        assertThrows(SessionNotFoundException.class,
                () -> service.routeFlow("does-not-exist", req(100L, 1L, List.of(1L, 4L))));
    }

    @Test
    void unknownPlayer_throwsIllegalArgument() {
        when(playerRepo.findById(999L)).thenReturn(Optional.empty());
        assertThrows(IllegalArgumentException.class,
                () -> service.routeFlow(session.getId(), req(999L, 1L, List.of(1L, 4L))));
    }

    @Test
    void playerInDifferentSession_throwsIllegalArgument() {
        GameSession otherSession = new GameSession();
        Player otherPlayer = new Player();
        otherPlayer.setSession(otherSession);
        when(playerRepo.findById(200L)).thenReturn(Optional.of(otherPlayer));

        assertThrows(IllegalArgumentException.class,
                () -> service.routeFlow(session.getId(), req(200L, 1L, List.of(1L, 4L))));
    }

    @Test
    void alreadyDeliveredFlow_throwsIllegalState() {
        flow.setStatus("DELIVERED");
        assertThrows(IllegalStateException.class,
                () -> service.routeFlow(session.getId(), req(100L, 1L, List.of(1L, 4L))));
    }

    @Test
    void pathDoesNotStartAtFlowSource_throwsIllegalArgument() {
        assertThrows(IllegalArgumentException.class,
                () -> service.routeFlow(session.getId(), req(100L, 1L, List.of(2L, 4L))));
    }

    @Test
    void pathDoesNotEndAtFlowDestination_throwsIllegalArgument() {
        assertThrows(IllegalArgumentException.class,
                () -> service.routeFlow(session.getId(), req(100L, 1L, List.of(1L, 5L))));
    }

    @Test
    void pathUsesNonExistentLink_throwsIllegalArgument() {
        // 1 and 4 are the flow endpoints, but go via 9 which has no links
        assertThrows(IllegalArgumentException.class,
                () -> service.routeFlow(session.getId(), req(100L, 1L, List.of(1L, 9L, 4L))));
    }

    @Test
    void validRoute_marksFlowDeliveredAndIncreasesLinkLoad() {
        service.routeFlow(session.getId(), req(100L, 1L, List.of(1L, 4L)));

        assertEquals("DELIVERED", flow.getStatus());
        verify(linkRepo, times(1)).save(argThat(l ->
                l.getSource().equals(1L) && l.getTarget().equals(4L) && l.getLoad() == 10));
    }
}