package com.packetquest.model;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * A weather or non-weather incident applied to the topology (e.g. a fibre cut,
 * node failure, electrical storm). Incidents are generated by the backend or the
 * Python simulator — never by the frontend. Carries the affected link types /
 * node ids / link ids and an optional visual zone so the frontend can render it.
 */
public class IncidentEvent {

    private String id = UUID.randomUUID().toString();
    private IncidentType eventType;
    /** What the incident targets: e.g. "NODE", "LINK", "ZONE". */
    private String targetType;
    private String targetId;
    private double severity;
    private String message;
    private Instant startedAt = Instant.now();
    private int durationSeconds;
    private Instant expiresAt;

    private List<LinkType> affectedLinkTypes = new ArrayList<>();
    private List<String> affectedNodeIds = new ArrayList<>();
    private List<String> affectedLinkIds = new ArrayList<>();
    private VisualZone visualZone;

    public IncidentEvent() {
    }

    public IncidentEvent(String id, IncidentType eventType, String targetType, String targetId,
                         double severity, String message, int durationSeconds) {
        this.id = id;
        this.eventType = eventType;
        this.targetType = targetType;
        this.targetId = targetId;
        this.severity = severity;
        this.message = message;
        this.durationSeconds = durationSeconds;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public IncidentType getEventType() {
        return eventType;
    }

    public void setEventType(IncidentType eventType) {
        this.eventType = eventType;
    }

    public String getTargetType() {
        return targetType;
    }

    public void setTargetType(String targetType) {
        this.targetType = targetType;
    }

    public String getTargetId() {
        return targetId;
    }

    public void setTargetId(String targetId) {
        this.targetId = targetId;
    }

    public double getSeverity() {
        return severity;
    }

    public void setSeverity(double severity) {
        this.severity = severity;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Instant getStartedAt() {
        return startedAt;
    }

    public void setStartedAt(Instant startedAt) {
        this.startedAt = startedAt;
    }

    public int getDurationSeconds() {
        return durationSeconds;
    }

    public void setDurationSeconds(int durationSeconds) {
        this.durationSeconds = durationSeconds;
    }

    public Instant getExpiresAt() {
        return expiresAt;
    }

    public void setExpiresAt(Instant expiresAt) {
        this.expiresAt = expiresAt;
    }

    public List<LinkType> getAffectedLinkTypes() {
        return affectedLinkTypes;
    }

    public void setAffectedLinkTypes(List<LinkType> affectedLinkTypes) {
        this.affectedLinkTypes = affectedLinkTypes != null ? affectedLinkTypes : new ArrayList<>();
    }

    public List<String> getAffectedNodeIds() {
        return affectedNodeIds;
    }

    public void setAffectedNodeIds(List<String> affectedNodeIds) {
        this.affectedNodeIds = affectedNodeIds != null ? affectedNodeIds : new ArrayList<>();
    }

    public List<String> getAffectedLinkIds() {
        return affectedLinkIds;
    }

    public void setAffectedLinkIds(List<String> affectedLinkIds) {
        this.affectedLinkIds = affectedLinkIds != null ? affectedLinkIds : new ArrayList<>();
    }

    public VisualZone getVisualZone() {
        return visualZone;
    }

    public void setVisualZone(VisualZone visualZone) {
        this.visualZone = visualZone;
    }
}
