package com.packetquest.model;

import java.time.Instant;
import java.util.UUID;

/**
 * A weather or non-weather incident applied to the topology (e.g. a fibre cut,
 * node failure, electrical storm). Incidents are generated by the backend (and,
 * later, the Python simulator) — never by the frontend.
 */
public class IncidentEvent {

    private String id = UUID.randomUUID().toString();
    private IncidentType eventType;
    /** What the incident targets: e.g. "NODE", "LINK", "AREA". */
    private String targetType;
    private String targetId;
    private double severity;
    private String message;
    private Instant startedAt = Instant.now();
    private int durationSeconds;
    private Instant expiresAt;

    public IncidentEvent() {
    }

    public IncidentEvent(String id, IncidentType eventType, String targetType, String targetId,
                         double severity, String message, int durationSeconds) {
        this.id = id;
        this.eventType = eventType;
        this.targetType = targetType;
        this.targetId = targetId;
        this.severity = severity;
        this.message = message;
        this.durationSeconds = durationSeconds;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public IncidentType getEventType() {
        return eventType;
    }

    public void setEventType(IncidentType eventType) {
        this.eventType = eventType;
    }

    public String getTargetType() {
        return targetType;
    }

    public void setTargetType(String targetType) {
        this.targetType = targetType;
    }

    public String getTargetId() {
        return targetId;
    }

    public void setTargetId(String targetId) {
        this.targetId = targetId;
    }

    public double getSeverity() {
        return severity;
    }

    public void setSeverity(double severity) {
        this.severity = severity;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Instant getStartedAt() {
        return startedAt;
    }

    public void setStartedAt(Instant startedAt) {
        this.startedAt = startedAt;
    }

    public int getDurationSeconds() {
        return durationSeconds;
    }

    public void setDurationSeconds(int durationSeconds) {
        this.durationSeconds = durationSeconds;
    }

    public Instant getExpiresAt() {
        return expiresAt;
    }

    public void setExpiresAt(Instant expiresAt) {
        this.expiresAt = expiresAt;
    }
}
