spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/packetquest}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:pquser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:pqpassword}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
